// eslint-disable-next-line import/no-anonymous-default-export
export default {
    experiment: 'Experiment',
    blocks: 'Blocks',
    blockDetails: 'Block Details',
    close: 'Close',
    hash: 'Hash',
    time: 'Time',
    height: 'Height',
    index: 'Index',
    size: 'Size',
    prev: 'Prev. Block',
    relayedBy: 'Relayed By',
    fee: 'Fee',
    inputs: 'Inputs',
    out: 'Out',
    unknown: 'Unknown',
    address: 'Address',
    spent: 'Spent',
    value: 'Value',
    sequence: 'Sequence',
    witness: 'Witness',
}